export const Images = [
  { Img: "./Assets/img1-men-s-black-slayer-squad.webp", name: "Men's Black Slayer Squad " },
  { Img: "./Assets/img2-mens-navy-blue-dark-knight.webp", name: "Men's Navy Blue Dark Knight" },
  { Img: "./Assets/img3-mens-black-hunter-x.webp", name: "Men's Black Hunter" },
  { Img: "./Assets/img4-men-s-black-hangin-astronaut.webp", name: "Men's Black Hangin Astraunaut" },
  { Img: "./Assets/img5-men-s-black-explorer-nasa.webp", name: "Men's Black Explorer Nasa" },
  { Img: "./Assets/img6-men-s-black-dementors.webp", name: "Men's Black Dementors" },
  { Img: "./Assets/img7-men-s-purpleseek-balance.webp", name: "Men's PurplSeek Balance" },
  { Img: "./Assets/img8-men-s-white-do-nothing.webp", name: "Men's White Do Nothing" },
  { Img: "./Assets/img9-men-s-black-hangin-astronaut.webp", name: "Men's Black Hangin Astraunaut" },
  { Img: "./Assets/img10.png", name: "Double Pocket Green" },
  { Img: "./Assets/img11.png", name: "Roadster Original" },
  { Img: "./Assets/img12.png", name: "Checs original" },
  { Img: "./Assets/img13.png", name: "Pink Checs" },
  { Img: "./Assets/img14.png" ,name: "Formal" },
  { Img: "./Assets/img15.png" ,name: "Floral" },
  { Img: "./Assets/img16.png" ,name: "Floral" },
  { Img: "./Assets/img17.png" ,name: "Black Casual" },
  { Img: "./Assets/img18.png" ,name: "Floral" },
  { Img: "./Assets/img19.png" ,name: "Floral" },
  { Img: "./Assets/img20.png" ,name: "Casual" },
];
